### ISSUE TITLE
List which plugins are working

### ISSUE THREAD

**Issue by ortonomy** [Hyperline/hyperline#112]
Looking at code, you have a few plugins like:
```
spotify
ip
time
party-parrot
git-status
```

but when I add these to they ``hyper.js`` config as so:

```
{
  name: 'git-status'
},
{
  name: 'time'
},
{
  name: 'ip'
}
```

Breaks loading of hyper.js

I'm on macOS Sierra latest

**Comment by timneutkens** [comment]
@ortonomy the beta version (with plugins) is a bit different from the currently released version.
