### ISSUE TITLE
Leftmost divider shows

### ISSUE THREAD

**Issue by ericmarkmartin** [Hyperline/hyperline#113]
There shouldn't be a divider for the leftmost plugin, but there is one, as can be seen below, both through the image itself and the devtools (`border-left-width` is `1px`).
<img width="1009" alt="screen shot 2017-08-26 at 9 04 40 pm" src="https://user-images.githubusercontent.com/5509414/29746258-403568d4-8aa2-11e7-9acf-0520885d2770.png">

**Comment by basedjux** [comment]
Hmm. I'll take a look into this.
Should have a fix for this by tomorrow!

**Comment by ericmarkmartin** [comment]
Thanks. I'm happy to help out if needed. It might also be worth mentioning that I'm running `hyperlink-magus` because I heard that was just a newer release (even though it seems not to have the Spotify plugin).

**Comment by timneutkens** [comment]
@ericmarkmartin we're working on a new version of hyperline in master 👌

**Comment by ericmarkmartin** [comment]
I could also probably deal with this if someone told me where they would like it to be fixed. I'm not too familiar with the structure of the project as it stands rn.
