### ISSUE TITLE
WMI Provider Host 

### ISSUE THREAD

**Issue by dzienisz** [Hyperline/hyperline#114]
I just notices that hyperline plugin create WMI Provider Host on my Windows 10 PC and use a lot of processor power for literally nothing.

![2017-08-29 13_58_25-menedzer zadan](https://user-images.githubusercontent.com/3521624/29819748-47a32594-8cc2-11e7-95c2-1280614b7524.png)

Also Antimalware Service is active during that WMI Provider Host time.

**Comment by basedjux** [comment]
Wow.. That's a serious amount of CPU usage.
Can you reply with your Windows 10 version and Hyper version? That will help me debug this. 

Thanks!

**Comment by dzienisz** [comment]
The nevewst windows and nevewst hyper (current)

29.08.2017 5:52 PM "Corbin Matschull" <notifications@github.com> napisał(a):

**Comment by basedjux** [comment]
Okay current versions of both, not a problem. 
Thanks. 

I will work on getting this debugged with a windows workstation.

**Comment by Xemiru** [comment]
I've narrowed it down to the `network` plugin causing the issue by isolating each of the stock plugins. When I launch Hyper with Hyperline configured to use everything _but_ `network`, this issue does not occur.

**Comment by basedjux** [comment]
Hmm very interesting. 
I'll do some research on WMI Host and how it inter-operates with the network plugin.

Thanks @Xemiru

**Comment by Cycymomo** [comment]
+1 @Xemiru 
Same here for your information on Windows 7

**Comment by iblazhko** [comment]
Same problem for me.
Windows 10 Pro 64-bit Version 1703, OS Build 15063.608
Hyper 1.4.6

Any chance to make refresh less frequent? I could not find any options to do this.

**Comment by basedjux** [comment]
Currently @iblazhko the only method to change refresh rate of the network plugin is to change:

```js
  componentDidMount() {
    this.getSpeed()
    this.interval = setInterval(() => this.getSpeed(), 1500)
    // ^ This line, change the number (in milliseconds) to desired number.
  }
```

We're working on a LOT better method of doing this coming in a new update.

**Comment by k9yosh** [comment]
I had the same issue, waiting for a fix. It's a really useful plugin. :)
