### ISSUE TITLE
hyper 2.0 support

### ISSUE THREAD

**Issue by seriouslyfluffy** [Hyperline/hyperline#120]
Got this when hyper launch :cry: 

![screenshot from 2017-09-20 20 35 51](https://user-images.githubusercontent.com/7502071/30658454-5f77f11c-9e43-11e7-8273-47e0a9c801a0.jpeg)

**Comment by basedjux** [comment]
Oh well that's very interesting. 
I'll take a look into it and report back. 

Thanks!

**Comment by Chinese1904** [comment]
when are you going to make this accessible for 2.0.* users?

**Comment by basedjux** [comment]
@Chinese1904, with #121, it will add Hyper v2 support; just have to wait for someone with write access to repo to merge it into master.

**Comment by Chinese1904** [comment]
That's why I was asking. I might fork this repo and make it usable again for v2 if this project seems dead.

**Comment by basedjux** [comment]
Haha @Chinese1904 I should ask them yes. 😉

**Comment by basedjux** [comment]
And for the meantime.. Yeah you could fork it.. Use the changes in #121 and then once we get it merged on our side you can use it that way.

**Comment by timneutkens** [comment]
@Chinese1904 if you want to help maintaining that'd be great. Lets talk on https://zeit.chat 🙌

**Comment by seriouslyfluffy** [comment]
thanks guys!)
