### ISSUE TITLE
Win7 100% CPU usage

### ISSUE THREAD

**Issue by jerodg** [Hyperline/hyperline#124]
Using windows 7 when I load the plugin, cpu usage spikes to 100% and stays pegged, however, no particular process can be found in task manager to associate that usage with.

**Comment by basedjux** [comment]
Hmm could be related to #114 🤔 

You can try modifying `src/lib/plugins/network.js:L49` thus: 
```js
  componentDidMount() {
    this.getSpeed()
    this.interval = setInterval(() => this.getSpeed(), 2500)
  }
```

I'm currently working on a fix that doesn't involve having to modifying the actual code.

**Comment by pratikone** [comment]
I am facing the same issue. Turning every setInterval to 5000 or more solves it. Even though there might be a bug, but I think having 500 ms for CPU status might be un-needed in most of the cases. Do you think changing it to 1000ms or more should be a good default for most of the users ?

**Comment by cgmx** [comment]
@pratikone I agree, I think 1k-5k milliseconds would be sufficient. I don't see a need to have the network plugin update every 0.5 seconds.
