### ISSUE TITLE
Line color not changing

### ISSUE THREAD

**Issue by mAsterEihaB** [Hyperline/hyperline#125]
Hey there :)

I've been facing an issue where I can't change the color of the line from black, I don't know what causes the issue and I hope you take a look at it.

**Comment by basedjux** [comment]
I'm assuming you mean the background color? 
Behind all of the plugins?

**Comment by mAsterEihaB** [comment]
yeah the color of the line itself

**Comment by JohnAllen** [comment]
Mine is just yellow.  Won't change no matter the color I specify.

**Comment by brunobmartins** [comment]
I'm also having the same trouble...

I've added the following to ~/.hyper.js

`hyperline: {
    color: 'white'
  }`

but it didn't worked.
I've also tried "different ways to pronounce white" with no luck...
