### ISSUE TITLE
hyperline overlaps with other plugin

### ISSUE THREAD

**Issue by Emanon42** [Hyperline/hyperline#126]
![image](https://user-images.githubusercontent.com/21653733/32181481-5a2cb766-bd8c-11e7-8011-f3373624c190.png)
I am using hyper-1.4.8-64bit on ubuntu 16.04LTS, I install hyperline and hyper-statusline but the display of these two plugins conflict.

**Comment by Emanon42** [comment]
![image](https://user-images.githubusercontent.com/21653733/32181669-d805a56c-bd8c-11e7-9a1b-464b29927650.png)

This is the effect of display when I only apply hyper-statusline.

**Comment by basedjux** [comment]
Well.. 
`hyper-statusline` and `hyperline` serve two purposes as of right now.
However! That being said, @henrikdahl and I are working to integrate `hyper-statusline` into `hyperline`.

That's a work in progress.
