### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by TheSETJ** [Hyperline/hyperline#128]
It's good if hyperline be more customizable. As far as I've investigated, I can't change font size, padding (or margin), border color and height of hyperline.

![image](https://user-images.githubusercontent.com/10893088/32370383-0c97f6fa-c0a2-11e7-8940-1cbc0c1a1ab8.png)

In my opinion, current visual of hyperline is not consistent.

I tried to edit hyperline.js, but it resets everytime I open Hyper.

**Comment by eshanmind** [comment]
I agree 100%

**Comment by rohitkrishna094** [comment]
Why was this issue closed without any solution posted? Is there a way to change font size or padding etc?
