### ISSUE TITLE
TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by jstnbchnn** [Hyperline/hyperline#132]
When opening Hyper after installing they hyperline plugin I get the following error. Any one have an idea of how to go about fixing this?

This is on OS X El Capitan

![image](https://user-images.githubusercontent.com/15064474/32790503-9e83e690-c92c-11e7-8749-bfde350c418d.png)

**Comment by cgmx** [comment]
#131 fixes this.
