### ISSUE TITLE
Hangs Spotify Closing ~Beta~

### ISSUE THREAD

**Issue by gabemeola** [Hyperline/hyperline#136]
The new spotify now playing tab is sweet.
Unfortunately it does prevent closing of spotify. :(

Repo:
1.  Open Hyper (Should say not running for Spotify)
2. Open Spotify
3. Try to close Spotify (should close then re-open in the background. You can still play / pause after re-open)

**Comment by digitaljhelms** [comment]
Curious why this was closed with no resolution? Currently on b4e275e6b399abff1540400d719f1169a77e3b30 and I still have this issue.
