### ISSUE TITLE
Vertical/Horizontal Scrollbars

### ISSUE THREAD

**Issue by kevintongg** [Hyperline/hyperline#137]
Updated to the new hyperline with the new design and I now have scrollbars.

**Comment by RoobieBoobieee** [comment]
Same here on W10.

**Comment by Grimones** [comment]
Same here on W10 too

**Comment by AndKenneth** [comment]
Same issue on macOS High Sierra

![screen shot 2018-01-05 at 11 44 49 pm](https://user-images.githubusercontent.com/5133959/34606053-c0c1bfe2-f272-11e7-836f-7698ca454a8d.png)

**Comment by Gevie** [comment]
If you use [hyper-stylesheet](https://www.npmjs.com/package/hyper-stylesheet) you can add the following css to temporarily fix this issue.

```
/* #window */
.hyperline_line {
        bottom: 6px !important;
        margin: auto !important;
}
```

**Comment by gluons** [comment]
Same on Linux Mint 18.3

**Comment by keremcankabadayi** [comment]
same macOs `10.13.2 Beta (17C79a)`

**Comment by TotomInc** [comment]
Looks like hyperline add by default a `margin: 10px 10px 0 10px` and sets itself with a `position: absolute` at `bottom: 1px`, you can override this by adding in your terminal CSS like @Gevie said:

```css
.hyperline_line {
  margin: 0;
  bottom: 0px;
}
```

Horizontal and vertical scrollbars will go away:

![image](https://user-images.githubusercontent.com/9285210/37279136-2f28caf2-25ea-11e8-8e96-52dd457bc33c.png)
