### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by rkichenama** [Hyperline/hyperline#138]
On linux mint 18.3 with hyper canary, and when I install hyperline, I get "couldn't find binary sh" error on install and when I set up a local plugin, it doesn't even load. Any help would be appreciated.

**Comment by rhogeranacleto** [comment]
So do I

**Comment by ben-alkov** [comment]
+1

**Comment by SanketDG** [comment]
Yup, happens with me too.

**Comment by rhogeranacleto** [comment]
I tried version `hyperline#0.6.1` and works!
