### ISSUE TITLE
How to remove Spotify and the Parrot ? 

### ISSUE THREAD

**Issue by Aarbel** [Hyperline/hyperline#141]
Hi Hyperline team !

How could i remove some options like Spotify and the Parrot ? Thanks ! :)

![image](https://user-images.githubusercontent.com/25119847/34361347-b0136cba-ea69-11e7-83c6-397e2ae54d81.png)

**Comment by alqahtani** [comment]
Me too :( 
at the last I installed the plugin locally in `~/.hyper_plugins/local` and edited the `src/lib/plugins/index.js` and commented out **Spotify** and **Party Parrot** and added **uptime**. also IP does not work for me and gave me (**?.?.?.?**) so I commented it too. 

---

this is my `src/lib/plugins/index.js` now:

```
import Hostname from './hostname'
// import Ip from './ip'
import Memory from './memory'
import Uptime from './uptime'
import Cpu from './cpu'
import Network from './network'
import Battery from './battery'
// Import Time from './time'
// Import Docker from './docker'
// import Spotify from './spotify'
// import PartyParrot from './party-parrot';

export default [Hostname, Uptime, Memory, Battery, Cpu, Network]
```

![screenshot](https://image.ibb.co/dSLTEw/Screen_Shot_2017_12_28_at_10_27_32_AM.png)

**Comment by jonjahr** [comment]
Is the party parrot a joke?  I appreciate party parrot, but cmon I don't wanna look at him all day.

**Comment by Jonic** [comment]
:+1: The Spotify thing might be useful for people that use Spotify, but is just using system resources for people that don't, and the parrot is just distracting! It's a fun idea, but maybe only suited to an Easter Egg?

It feels like Hyperline might now have enough stuff bundled in it that a config object to enable/disable these things would be useful. I might have a go at a PR for that.

**Comment by river226** [comment]
Agreed, a quick config would be nice I don't use spotify, sort annoying that it's just there. Also the party parrot is super annoying and distracting... maybe just kill that.

**Comment by arshdkhn1** [comment]
If you want to hide it then you can do the following things - 

1. Install [hyper-stylesheet](https://github.com/chrisdothtml/hyper-stylesheet)

Add to the plugins array in your .hyper.js:
```
plugins: [
  'hyper-stylesheet'
]
```

2. Add following lines to `~/.hyper.css` after `/* #window */` comment line.
```css
/* remove parrot, spotify from hyperline */
.hyperline_line .spotify_wrapper, .hyperline_line .partyparrot_wrapper {
        display: none;
}
```

You can inspect the hyperline component in devtools to hide whatever component that you want to hide.

**Comment by NickTikhonov** [comment]
This has been fixed with https://github.com/Hyperline/hyperline/pull/146
