### ISSUE TITLE
Beta versions should be tagged as beta on npm

### ISSUE THREAD

**Issue by einfallstoll** [Hyperline/hyperline#142]
By default npm installs `hyperline@latest` which is currently `1.0.0-beta.1.2`. It would make more sense to tag `0.6.1` as `hyperline@latest` and `1.0.0-beta.1.2` as `hyperline@beta`.

This should do the trick, devs:

    npm dist-tag add hyperline@0.6.1 latest
    npm dist-tag add hyperline@1.0.0-beta.1.2 beta

This would fix #140, #134 and #127

**Comment by AndKenneth** [comment]
For anyone scanning this, adding `hyperline#0.6.1` to the plugins section of your hyper.js file will roll you back to a working version. Hope the above is implemented.

**Comment by tsaiDavid** [comment]
This is a sensible suggestion, properly tagging here would prevent a whole lot of issues showing up!
