### ISSUE TITLE
Add git branch module

### ISSUE THREAD

**Issue by TotomInc** [Hyperline/hyperline#148]
Add the support to show the current git branch in the status bar.

**Comment by keremcankabadayi** [comment]
+1

there is a [plugin](https://www.npmjs.com/package/hyper-statusline) for that. But i want to combine these two.

**Comment by TotomInc** [comment]
@keremcankabadayi that was my initial idea, combine what `hyper-statusline` does to have only one module which add a status-bar. Having 2 status bar at once is not really esthetic. I'll see what I can do for a PR. 😄

**Comment by iamjaredwalters** [comment]
Any progress on this?
