### ISSUE TITLE
OpenCollective causes error in Archlinux

### ISSUE THREAD

**Issue by dragonJACson** [Hyperline/hyperline#149]
Hyper Version: 2.0.0.canary.14

hyper.js:
```javascript
plugins: [
  `hyperline`,
  `...`
]
```

Using `Hyper -v`, it shows:
```
[Notification] Error updating plugins.: error /home/luke/.hyper_plugins/node_modules/hyperline: Command failed.
Exit code: 127
Command: opencollective postinstall
Arguments:
Directory: /home/luke/.hyper_plugins/node_modules/hyperline
Output:
/usr/bin/env: 'node': No such file or directory
```

Related Link:
https://bbs.archlinux.org/viewtopic.php?id=168479

**Comment by neojski** [comment]
I have the same problem. I have just installed hyper using the "contributing" guide and hyperline doesn't work.

**Comment by xster** [comment]
Same issue on macOS

**Comment by plibither8** [comment]
Facing a similar problem on Ubuntu 16.04

**Comment by dragonJACson** [comment]
Now the `hyperline` will show the same error as before, but it works, so I closed this issue.
