### ISSUE TITLE
Modules can't be found in Hyper 1.4.8

### ISSUE THREAD

**Issue by goldquest** [Hyperline/hyperline#152]
On start of Hyper, a notification pops up, that `react` couldn't be found.
I cloned this plugin locally and introduced react, but now it says, that hyper/component is missing.

I guess hyper doesn't provide these packages anymore?

https://github.com/Hyperline/hyperline/blob/3346645271179e2b6eae00e587a9883cdf4ea52d/webpack.config.js#L13

**Comment by scerelli** [comment]
I get this too

**Comment by goldquest** [comment]
Ok. Apparently hyper hijacks the module loading system: https://github.com/zeit/hyper/blob/1.4.8/lib/utils/plugins.js#L21. The error thrown here seems to be a bug of hyper.

**Comment by R0uter** [comment]
@abhishekchotaliya 
>moving the hyperline configuration below plugins 
It worked! thx.
But some how, hyperline do not read config `hyperline: { plugins: [ "ip", "cpu", "spotify" ] },`  :(

**Comment by goldquest** [comment]
So since we have hyper2 stable now, I would say this issue is obsolete. Let's just make this plugin work for hyper2 now.
Ongoing issue about that: https://github.com/Hyperline/hyperline/issues/150
