### ISSUE TITLE
I miss the parrot

### ISSUE THREAD

**Issue by ftovaro** [Hyperline/hyperline#154]
Is there any way to reactivate the parrot or has it been completely eliminated? I loved him 😢

**Comment by TheDonDope** [comment]
https://github.com/Hyperline/hyperline/commit/e824b49d55c7dacd3ef9f5b989682abffcc8c899 killed the parrot :C
You could restore it, if you would partially revert the changes of this commit (Browse through the changeset and you will find the corresponding code).

**Comment by ftovaro** [comment]
Thank you 👍

**Comment by TheDonDope** [comment]
@ftovaro I just saw that the parrot was moved to a separate repository: https://github.com/Hyperline/party-parrot-hyperline

So maybe you don't even need to fiddle around manually and just can add this as a separate Hyper plugin?
