### ISSUE TITLE
Uncaught Error EPIPE & Osascript Makes Hyper Lagging on Ubuntu

### ISSUE THREAD

**Issue by malwareslayer** [Hyperline/hyperline#168]
Hyperline keep getting Uncaught Error like this below, and makes Hyper Lagging

`events.js`
```
Uncaught Error: spawn osascript ENOENT
    at exports._errnoException (util.js:1024)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192)
    at onErrorNT (internal/child_process.js:374)
    at _combinedTickCallback (internal/process/next_tick.js:138)
    at process._tickCallback (internal/process/next_tick.js:180)
```

```
Uncaught Error: write EPIPE
    at exports._errnoException (util.js:1024)
    at WriteWrap.afterWrite [as oncomplete] (net.js:851)
```

**Comment by miguelfaggioni** [comment]
Same issue on Windows 10 :(

**Comment by keremcankabadayi** [comment]
any news about it?

**Comment by mwoz123** [comment]
problem still exists :(
I keep on getting this on :

```
marcin@hp:~$ uname -a
Linux hp 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
marcin@hp:~$ lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
marcin@hp:~$ 
```
hyper version: 
```
$ hyper version
3.1.2
```
Details: 
![Zrzut ekranu z 2021-09-04 13-45-51](https://user-images.githubusercontent.com/4487025/132093338-bd582b28-c83f-446d-8611-d4cef9cf30f1.png)

**Comment by mwoz123** [comment]
this might be helpfull: 

https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

**Comment by malwareslayer** [comment]
Close issues, because `osascript` is only in MacOS, that's why there's no Linux distribution has `osascript` either backported into Linux distribution.

**Comment by mwoz123** [comment]
@malwareslayer - is there a solution/workaround for that ? 
Shouldn't then this `osascript` check/use only on Macs? 

The issue still exists on Linux...

moreover I do confirm it's also exist on Windows: 

![image](https://user-images.githubusercontent.com/4487025/134342692-b1d9a09a-a523-43cd-b78e-9da4901a3d92.png)


it seems the only env where it doesn't is Mac ...
