### ISSUE TITLE
Hyperline won't load config

### ISSUE THREAD

**Issue by asbarron** [Hyperline/hyperline#179]
I edited `.hyper.js` as described in `README.md`:
``` javascript
  plugins: ["hyperpower", "hyperline"],

  config: {
    hyperline: {
      plugins: [
        "ip",
        "cpu",
        "spotify"
      ]
    },
  }, 

  localPlugins: [],

  keymaps: {
    // Example
    // 'window:devtools': 'cmd+alt+o',
  },
};```

**Comment by Erchoc** [comment]
> I edited `.hyper.js` as described in `README.md`:
> 
> ```js
>   plugins: ["hyperpower", "hyperline"],
> 
>   config: {
>     hyperline: {
>       plugins: [
>         "ip",
>         "cpu",
>         "spotify"
>       ]
>     },
>   }, 
> 
>   localPlugins: [],
> 
>   keymaps: {
>     // Example
>     // 'window:devtools': 'cmd+alt+o',
>   },
> };```
> ```

why closed?
