### ISSUE TITLE
Adding the setInterval delay to the config

### ISSUE THREAD

**Issue by AddictArts** [Hyperline/hyperline#36]
If anyone is looking for an enhancement I would ask for this feature. I have found the memory checking every 100ms aggressive and ended up hacking the dist bundle. I don't have time to fork and pull request, wish I did. Thanks

I also found the network check aggressive and drives my cpu usage up. On my Mac the fans kick in like I'm running OpenGL rendering in a window. This is on Yosemite. Using the config I just eliminated the network by not including it, thanks for that. It also listed "NaN" intermittently if someone is looking for that.

**Comment by davegomez** [comment]
I agree on the time interval part and I will check the network NaN output.

**Comment by NickTikhonov** [comment]
Hey @AddictArts - thank you for flagging up these issues. It's a good idea to provide ability to configure the intervals, and have a better default. One of us will look into this.

**Comment by timneutkens** [comment]
The NaN fix was already merged (#38)

**Comment by NickTikhonov** [comment]
@AddictArts - I wrote a solution to this problem in #40 :)

With the next HyperLine release, you will be able to set update intervals on a per-plugin basis.
