### ISSUE TITLE
Apply styles using classes

### ISSUE THREAD

**Issue by davegomez** [Hyperline/hyperline#37]
We are using inline styles for Hyperline making the resulted code big, confusing, ugly, and difficult to override. I think we should use classes instead to apply the styles.

I'm not sure how this is being done with Hyperterm but it worth to look at it.

**Comment by timneutkens** [comment]
Just looked into this, you're making such a valid point. Thanks for bringing it up.
Will take a deep dive into it later.

**Comment by kaicataldo** [comment]
Was just looking at this to try to make the font-weight not bold. Applying styles with classes/having an option to apply styles would be great!

**Comment by timneutkens** [comment]
@kaicataldo I started working on this, haven't had much time lately. The fontWeight option wouldn't be needed if I implement classnames.

**Comment by timneutkens** [comment]
Fixed in the `develop` branch.
