### ISSUE TITLE
Ideas for Hyperline items (plugins)

### ISSUE THREAD

**Issue by timneutkens** [Hyperline/hyperline#41]
Do you have a great idea for a new plugin? Post it below please 😄

**Comment by timneutkens** [comment]
Taken from #4 
- Resizable line
- Git information (Branch/Last Commit Id/Staged & Unstaged count)
- Clickable buttons (for example: Editor button used to open current directory in your favorite editor)
- Something I just thought of is expandable menus or sections to show more options or information
- Some kind of summary of running / detached processes

**Comment by aewing** [comment]
Network usage would be a nice addition.

**Comment by pthrasher** [comment]
Definitely VCS (git, hg, svn, etc) information.

**Comment by Pangoraw** [comment]
I created a plugin which gather the temperature from the `Yahoo API`. However I am not sure if I should do a pull request, as this plugin pretty different in purpose than what is installed by default with `hyperline`.
![hyperline](https://cloud.githubusercontent.com/assets/9824244/20649382/1c4bb64e-b4bf-11e6-8e95-dfbc9153066d.png)
Tell me if you wan't me to make a pull request.

**PS**: I am still looking for a better icon, this one doesn't scale properly and doesn't look like the others.

**Comment by timneutkens** [comment]
@pangoraw Sure thing 👍 Just make sure you make it configurable. Disabled by default since it does http(s) requests which people might not want.

**Comment by hellominotaur** [comment]
I would like it if (and have written code to do this in my fork) `user@hostname` could be displayed, with some options to switch the user on or off

If you think that might be what other people might want I can swing a PR over

**Comment by egeriis** [comment]
It would be neat if there was an ability to write plugins without having to have it added to this core repo. Maybe even have all core plugins in separate modules, e.g. `hypertext-hyperline-battery`.

A feature idea for these plugins would be the ability to act contextually on the current path. Like _git status/branch_ would act only if the current path contains a repo, it could be fun to do plugins that are activated when sitting in e.g. a JavaScript project.

**Comment by egeriis** [comment]
A convention could be established that hyperline would look for plugins, not only in `lib/plugins` but fall back to look for a module installed through npm named `hypertext-hyperline-{plugin-name}`. Not sure if this is the proper place for this discussion though :)

**Comment by timneutkens** [comment]
@egeriis hyper has all the plug-in management stuff built in, so we can just built upon that. I'm still working on a rewrite of the codebase to allow this + a lot cleaner code And customisation with css instead of configuration. Just give me a little time. Currently quite busy with other stuff :) your input is much appreciated though, keep it coming 😎

**Comment by egeriis** [comment]
@timneutkens Feel free to let me know if I can contribute. I think there's some potential to do some work that would benefit here, so I'm prepared to contribute where can.

**Comment by timneutkens** [comment]
@egeriis be Sure to join the zeit slack And send me a message :)

**Comment by egeriis** [comment]
What, how, where? :)

**Comment by timneutkens** [comment]
https://zeit.chat

**Comment by Pangoraw** [comment]
Good idea ! Because, for exemple my temperature plugin is vulnerable to `yahoo API` updates (it has already been broken twice) so I don't know if it should be part of the main repo.

**Comment by piclemx** [comment]
That could be cool to put the time!

**Comment by pagameba** [comment]
Docker status (something like https://github.com/adrianmo/powerline-docker)

**Comment by nikhilesh20** [comment]
Can we have spotify status like hyper-spotify?

**Comment by timneutkens** [comment]
@nikhilesh20 that's already there in the beta version 😄

**Comment by timneutkens** [comment]
Going to close this.
