### ISSUE TITLE
Implement css icon set

### ISSUE THREAD

**Issue by timneutkens** [Hyperline/hyperline#49]
@davegomez Might be nice to implement pure css icons 😏 
http://cssicon.space/#/icon/search

I'm fine with the current solution though. But it might cleanup markup a bit 👍

**Comment by davegomez** [comment]
I personally prefer SVG icons, also I don't like the way we have to implement CSS at the moment (inline). Also CSS icons are more difficult to maintain since there is more code involve and can't modify using a graphic tool.

**Comment by timneutkens** [comment]
Hey Dave,
The fix I made for exposing the wrapper component in hyperterm is added in 8.2 (at least I think so.) So I can start integrating it soon 😄 
The css icons is just an idea 👍
