### ISSUE TITLE
add windows support

### ISSUE THREAD

**Issue by luisrudge** [Hyperline/hyperline#57]
`systeminformation` doesn't work on windows :(

**Comment by timneutkens** [comment]
Well that's not too good 😅

**Comment by davegomez** [comment]
Is not easy to get all this information from Windows platform, at least many of the native Node.js tools doesn't work properly on Windows.

**Comment by luisrudge** [comment]
Yeah.. I figured.. 😝

**Comment by Equinox** [comment]
[This looks extremely promising, though!](https://github.com/sebhildebrandt/systeminformation/commit/b2b9f7928ff9e8786b8fb75e29ff7ebb7c61e4ad)

**Comment by meffect** [comment]
can you add notes that this plugin doesnt work on windows. I spent a couple hours until I found this

**Comment by DanielGGordon** [comment]
Yes please add on the top of the README that this is not supported on Windows.

**Comment by kierenj** [comment]
..Works fine for me, with the exception of RAM info.

**Comment by jose-a-sa** [comment]
For me some times works and other times doesn't

**Comment by zaucy** [comment]
[systeminformation](https://github.com/sebhildebrandt/systeminformation) works (sort of) on windows. I'd close this issue and any problems on windows should directed to the [systeminformation issues](https://github.com/sebhildebrandt/systeminformation/issues).

**Comment by mattwoolnough** [comment]
Continually throws following error in Windows 10: 
```
Uncaught Error: Command failed: route get 0.0.0.0 2>/dev/null | grep interface: | awk '{print $2}'
The system cannot find the path specified.
```

**Comment by kamisamamizu** [comment]
It is surprising to see this issue.
Hyperline has been working almost perfectly for me.
Only issue I have is that the network info is always at 0kB/s, but the ram, uptime, CPU and battery indicators work.

**Comment by timneutkens** [comment]
@kamisamamizu 💯 nice

**Comment by lonesome-rider** [comment]
It seems to work for me, but I have two freaking scrollbars all the time.
By the way, the little dancing bird and the spotify icon are normal?
