### ISSUE TITLE
Display Git information

### ISSUE THREAD

**Issue by Connorelsea** [Hyperline/hyperline#62]
My idea would be to separate related sections of git info into separate hyperline plugins. 

- `git-diff` : Shows the additions and deletions (in # of lines) of the current working directory 
- `git-path-status` : Shows stats about the current working directory (is staged, is ignored, is modified, is new)
- `git-branch` : Shows the name of the current branch

I'd be interesting in implementing this and submitting a PR if that is okay with the maintainers.

We could possibly use [this library](https://www.npmjs.com/package/simple-git).

**Comment by timneutkens** [comment]
@Connorelsea Fine idea. Go for it :shipit:

**Comment by amandeepmittal** [comment]
@Connorelsea +1

**Comment by NickTikhonov** [comment]
@Connorelsea great idea - providing a way of moving git information away from the prompt and into the status bar could be useful for a lot of people!

**Comment by Anahkiasen** [comment]
I tried to take a shot at it with [git-repo-info](https://github.com/rwjblue/git-repo-info) but I bumped into two issues:

1. I'm not entirely sure how to get the cwd from one of the plugin's perspective, looked in the component's context and all but I can't find where that info would be
2. Currently as the components are not tied to the cwd, the components do not re-render when the user changes folder

Now both of those are most likely doable but, I didn't have enough time to properly look further, if someone else wants to take a look.

**Comment by timneutkens** [comment]
@Anahkiasen https://github.com/henrikdahl/hyper-statusline has git info. Take a look at that source 😄, if you're going to add it. Please do it in the `develop` branch.

**Comment by Anahkiasen** [comment]
Yes that's the plugin I looked at (because originally I thought I could use both but they overlap each other) but as far as I can see it handles this in an entirely different way from the way Hyperline is architectured :/

**Comment by timneutkens** [comment]
@Anahkiasen me, @NickTikhonov and @henrikdahl have plans to combine the two status lines. Just haven't had time to implement it all 😄 I'll have a look when I get to it :)

**Comment by henrikdahl** [comment]
I've lacked time as well. I'll also look into it when I find time ✌️

**Comment by sangdth** [comment]
Please, this feature is awesome.

**Comment by basedjux** [comment]
@sangdth this feature is being worked on by @henrikdahl and myself.
Henrik has this feature already in a [statusline plugin](https://github.com/henrikdahl/hyper-statusline) of his own so it's mainly the process of getting it ported over to Hyperline.

**Comment by sangdth** [comment]
Thanks for your fast response @basedjux, I came here after installed the statusline plugin but it was covered by hyperline. Looking forward. Thanks for all your contribution.

**Comment by basedjux** [comment]
Yeah no problem 😄 

And yeah you can't have them both running, it has to be one or the other for right now.

**Comment by FranklinYu** [comment]
Why this was closed? Is this feature implemented?
