### ISSUE TITLE
Option to set the position.

### ISSUE THREAD

**Issue by luangch** [Hyperline/hyperline#66]
Need an option to pull it to the bottom right of the window.

**Comment by BirkhoffLee** [comment]
+1

**Comment by ashrithr** [comment]
+1

**Comment by timneutkens** [comment]
Will add this to the new version 👍

**Comment by coleman17** [comment]
+1 thanks!

**Comment by piotryordanov** [comment]
@timneutkens Is this coming to the new version? :)

**Comment by basedjux** [comment]
That's the idea @piotryordanov 👍

**Comment by janjur** [comment]
@NickTikhonov , so how can I align to the right?

**Comment by mayconaraujosantos** [comment]
I changed the dist file
in **C:\Users\myUserName\AppData\Roaming\Hyper\.hyper_plugins\node_modules\hyperline\dist\hyperline.js**

css: ['.line.jsx-1196914242{ justify-content: center;display:flex;align-items:center;position:absolute;overflow:hidden;bottom:0;width:100%;height:18px;font:bold 10px Monospace;pointer-events:none;background:rgba(0,0,0,0.08);margin:5px 0;padding:0 10px;}', '.jsx-1196914242,.wrapper.jsx-1196914242{display:flex;flex-shrink:0;align-items:center;padding-left:10px;padding-right:10px;}']

add **justify-content: center**
