### ISSUE TITLE
hyperline covers my terminal content

### ISSUE THREAD

**Issue by BirkhoffLee** [Hyperline/hyperline#70]
as the picture, see the last line

![screen shot 2017-01-07 at 2 54 52 pm](https://cloud.githubusercontent.com/assets/8148095/21740098/6306f7b6-d4e9-11e6-86f0-da6e337eea9d.png)

**Comment by ashrithr** [comment]
Same here.

**Comment by timneutkens** [comment]
@BirkhoffLee Could you try this in your `~/.hyper.js`: `padding: '12px 14px 18px 14px'`

**Comment by timneutkens** [comment]
We'll implement a new design in the new version. I'll make sure it's fixed 👍

**Comment by BirkhoffLee** [comment]
@timneutkens Adding `padding: '12px 14px 18px 14px'` to `~/.hyper.js` is working. Thanks for the workaround.

**Comment by timneutkens** [comment]
@BirkhoffLee 👍

**Comment by timneutkens** [comment]
I'm keeping this open for people having the same issue / as a reminder till I fix it 👍

**Comment by littleStudent** [comment]
just ran into this issue. The padding at the bottom varies depending on the configured font + font-size.

**Comment by benjamin-rood** [comment]
@littleStudent You're right, unfortunately. I find that `padding: '.5rem .5rem 1.2rem .5rem'` is 100% safe but kinda ugly. 
`padding: '.5rem .5rem .8rem .5rem'` is more reasonable.

**Comment by mackelito** [comment]
Should not the markup be placed in the <footer> ?

**Comment by basedjux** [comment]
@BirkhoffLee 
Fix created in #111 
🎉

**Comment by nemo** [comment]
@basedjux tried updating and I still get it o_O

**Comment by basedjux** [comment]
Really, @nemo? 
Hmm. Can you post a screenshot of the issue, please? Thanks 😄
