### ISSUE TITLE
Not able to change Background Color

### ISSUE THREAD

**Issue by gabrielboliveira** [Hyperline/hyperline#72]
No matter which color I configure, it always keeps a black background. 

I'm using [cobalt2 theme](https://github.com/wesbos/hyperterm-cobalt2-theme), which changes the terminal background color to `#193549`.

Tried to change both color and background attribute, with no success.

![hyperterm with background](https://cloud.githubusercontent.com/assets/11093090/22261240/5041e88a-e253-11e6-82e1-e5d64fcd655c.png)

**Comment by timneutkens** [comment]
Hi, could you try the develop branch? https://github.com/Hyperline/hyperline/tree/develop

**Comment by gabrielboliveira** [comment]
@timneutkens looks like it fixed, seems very different. But the plugin keeps failing with a "react" issue:

![hyperline react issue](https://cloud.githubusercontent.com/assets/11093090/22264649/e9471ea4-e25f-11e6-9f13-a90313737b46.png)

**Comment by timneutkens** [comment]
Hmm that's interesting. I'll have a look into that!
Yeah I'm doing a full rewrite. Merging with https://github.com/henrikdahl/hyper-statusline and adding custom plugins, so you'll be able to create your own Hyperline plugins 🔜  👍

**Comment by gabrielboliveira** [comment]
That's nice! I liked the new interface. Give me a heads up when a new update comes, I'll test it

**Comment by timneutkens** [comment]
Thanks!

**Comment by Sinequanonh** [comment]
Hey @timneutkens! Thanks for your work. I would love to use both hyperline along with hyper-statusline! Where are you at?
Best!
