### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by designMoreWeb** [Hyperline/hyperline#75]
Hyperline is not showing up i have installed it and have configured it however doesn't show up in the console. 

module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 15,

    // font family with optional fallbacks
    fontFamily: 'Miso Light,Hack, "DejaVu Sans Mono", "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BEAM',

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    shell: '',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false,

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',
 hyperline: {
      color: 'black',
      plugins: [
        {
          name: 'hostname',
          options: { color: 'lightBlue' }
        },
        {
          name: 'memory',
          options: { color: 'white' }
        },
        {
          name: 'uptime',
          options: { color: 'lightYellow' }
        },
        {
          name: 'cpu',
          options: {
            colors: {
              high: 'lightRed',
              moderate: 'lightYellow',
              low: 'lightGreen'
            }
          }
        },
        {
          name: 'network',
          options: { color: 'lightCyan' }
        },
        {
          name: 'battery',
          options: {
            colors: { fine: 'lightGreen', critical: 'lightRed' }
          }
        }
      ]
    }

    // for advanced config flags please refer to https://hyper.is/#cfg
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: [
    "hypertheme",
    "hyperline",
    "hyperterm-paste",
    "hyper-materialshell",
    'hyperterm-tabs',
    'hypertitle',
    'hyperterm-tab-icons',
    'hyper-font-smoothing',
    'hyper-simple-vibrancy'
  ],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins:[]
};

thats my config file

<img width="863" alt="screen shot 2017-02-23 at 4 23 34 pm" src="https://cloud.githubusercontent.com/assets/5986856/23279755/7541ad7a-f9e4-11e6-9f48-32d1c5808359.png">

**Comment by designMoreWeb** [comment]
Main issue is with 
<img width="1626" alt="screen shot 2017-02-23 at 5 31 33 pm" src="https://cloud.githubusercontent.com/assets/5986856/23282139/f955c994-f9ed-11e6-8a58-b6f80e4337ce.png">

Public-Ip is not in the github repo

**Comment by basedjux** [comment]
First, what version of NPM are you/did you using/use?


Also, you might try this; Hyper might be mangling the NPM install:

```bash
cd ~/.hyper_plugins

npm install
```
