### ISSUE TITLE
Add an option to disable the battery display

### ISSUE THREAD

**Issue by Keepco** [Hyperline/hyperline#84]
Hello,
sorry if this is already possible (and mentioned somewhere), but I couldn't find something about this.
It would be great if there was a way to disable the battery display, as it's pretty much useless for desktops.

**Comment by slinto** [comment]
@Keepco just edit a hyperline config.

**Comment by basedjux** [comment]
@Keepco the only method of removing it right now (that I've found) is going into [src/lib/plugins/index.js](https://github.com/Hyperline/hyperline/blob/master/src/lib/plugins/index.js) and removing ```Battery``` from the default export array, also comment out the import statement for battery:
```js
import Battery from './battery'
```
If you do NOT do this the linter will complain at you.

**Comment by timneutkens** [comment]
Thanks @basedjux, we'll support plugins soon 👌
