### ISSUE TITLE
Display status of remote machine

### ISSUE THREAD

**Issue by bshibley** [Hyperline/hyperline#85]
I most commonly use Hyper to login to remote systems using mosh.  It would be awesome if the status bar could be configured to show the system status of the remote system (rather than the local system) of the active tab's remote (ssh/mosh/telnet) session.

**Comment by avshyz** [comment]
+1. That would be awesome.

**Comment by basedjux** [comment]
Working on this implementation.

**Comment by marshalhayes** [comment]
+1 in 2018 😄

**Comment by vasilescur** [comment]
What's the status on this?
