### ISSUE TITLE
Use CPU Load instead of CPU Percentage

### ISSUE THREAD

**Issue by CrazyPython** [Hyperline/hyperline#94]
It's a much more useful measure of processor load. The last three numbers of `uptime` show load:

```
15:30  up 1 day,  2:52, 1 user, load averages: 7.48 18.32 11.88
```

(5 min, 10 min, 15 min)

**Comment by basedjux** [comment]
This is already implemented:
https://github.com/Hyperline/hyperline/blob/master/src/lib/plugins/cpu.js#L60


```js
  getCpuLoad() {
    cpuLoad().then(({ currentload }) => this.setState({
      cpuLoad: leftPad(currentload.toFixed(), 3, 0)
    }))
  }
```

**Comment by basedjux** [comment]
Oh I see what you're talking about, my apologies @CrazyPython.

**Comment by basedjux** [comment]
Working on this change right now

**Comment by timneutkens** [comment]
Amazing 👌 👍

**Comment by basedjux** [comment]
Issue resolved in #99

**Comment by CrazyPython** [comment]
It looks like this issue has been implemented.

**Comment by timneutkens** [comment]
:ok_hand:
