### ISSUE TITLE
Lint errors trying to run `npm run build`

### ISSUE THREAD

**Issue by snowinferno** [Hyperline/hyperline#95]
Cloned to try and find out why the npm module didn't include plugins available in GH (e.g. Spotify) and encountered the following error trying to run `npm run build`

```
ERROR in ./src/lib/plugins/docker.js
ESLintError:
/Users/snowinferno/.hyper_plugins/local/hyperline/src/lib/plugins/docker.js
  51:15  error  'err' is defined but never used  no-unused-vars
  70:25  error  Trailing spaces not allowed      no-trailing-spaces

✖ 2 problems (2 errors, 0 warnings)
```

Locally changing line 51 to be `      .catch( () => {` and removing trailing space from line 70 fixed the build and everything appears to work as expected.

**Comment by basedjux** [comment]
@snowinferno I fixed this in #96, pull and build again.
