### ISSUE TITLE
Expose plugins list to allow user to add/remove plugins.

### ISSUE THREAD

**Issue by basedjux** [Hyperline/hyperline#97]
Something that I'm currently working on but figured I'd put it here is:

Exposing the plugins list to be customizable by the user; currently a user has to open src/lib/plguins/index.js and remove the plugin from the 
```js 
export default []
``` 
list, and then comment out the import statement so the linter won't complain.

I did notice in src/lib/utils/config.js this seems to be an in-dev implementation of what I'm describing, I'd love confirmation on whether or not this is correct.

**Comment by timneutkens** [comment]
@basedjux we can provide each plugin as standalone hyper plugin.

**Comment by timneutkens** [comment]
@stefanivic has been working on the first. Which will be a boilerplate for the other plugins 👌

**Comment by timneutkens** [comment]
The latest version of hyperline supports external plugins btw 😄

**Comment by basedjux** [comment]
Ahh that's how that will be implemented, okay! Cool! I will just wait patiently then for that boilerplate to come along then.

And yeah I did see that with latest ver of Hyper! 😃

**Comment by timneutkens** [comment]
Feel free to join https://zeit.chat/ and send me a message 👍

**Comment by basedjux** [comment]
Closing this issue. 
@timneutkens and I spoke and his team and himself are implementing something a lot more simple.
